CHOICES = [
	("Afghanistan","Afghanistan" ),
 	("Albania", "Albania"),
	("Algeria", "Algeria"),
	("Andorra", "Andorra"),
	("Angola", "Anglola"),
	("Antigua and Barbuda", "Antigua and Barbuda"),
	("Argentina", "Argentia"),
	("Armenia", "Armenia"),
	("Australia", "Australia"),
	("Austria", "Austria"),
	("Azerbaijan", "Azerbaijan"),
	("Bahamas", "Bahamas"),
	("Bahrain", "Bahrain"),
	("Bangladesh", "Bangladesh"),
	("Barbados", "Barbados"),
	("Belarus", "Belarus"),
	("Belgium", "Belgium"),
	("Belize", "Belize"),
	("Benin", "Benin"),
	("Bhutan", "Bhutan"),
	("Bolivia", "Bolivia"),
	("Botswana", "Botswana"),
	("Brazil","Brazil"),
	("Canada","Canada"),
	("United Arab Emirates", "United Arab Emirates"),
	("United Kingdom","United Kingdom"),
	("United States of America", "United States of America"),
	("Uruguay", "Uruguay"),
	("Uzbekistan","Uzbekistan"),
	("Vanuatu","Vanuatu"),
	("Venezuela","Venezuela"),
	("Vietnam","Vietnam"),
	("Yemen", "Yemen"),
	("Zambia", "Zambia"),
	("Zimbabwe","Zimbabwe")

]